version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:13306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  web:
    build: .
    ports:
      - "8080:8080"
    links:
      - db
    volumes:
      - ./app:/app
    command: bash /app/start.sh
