version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - "13306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'demo'
  web:
    build: .
    ports:
      - "8080:8080"
    links:
      - db
    volumes:
      - ./app:/var/www/app
    command: bash /var/www/app/start.sh
